# Generated by Django 4.1.13 on 2025-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
